### ISSUE TITLE
2d karte: änderung der mitarbeiter-anzeige in Räumen

### ISSUE THREAD

**Issue by Michael-Stuehle** [Michael-Stuehle/wilken_maps#25]
aktuell werden beim mouse-over über einem Raum dessen mitarbeiter im Raum angezeigt.
das problem dabei ist, dass diese schlecht sichtbar sind, ab eine gewisse menge an mitarbeitern in einem raum sind.
![image](https://user-images.githubusercontent.com/58933430/101336773-26526900-387b-11eb-9055-d60221d56283.png)

meine Änderungs-Idee wäre, dass beim mouse-over sich beim Raum selber nur die farbe/schriftgröße ändert.
die Mitarbeiter würden dann nicht mehr im Raum angezeigt werden, sondern es sollte einen "Seitenstreifen" geben wo diese dann ein feld bekommen. außerdem sollten dann die felder für start/ziel und suchen hierher verschoben werden. (so wie bei google maps eben)
![image](https://user-images.githubusercontent.com/58933430/101337631-328af600-387c-11eb-8845-518e289deb02.png)

**Comment by bewerne** [comment]
Wie wäre es mit eine Zoom-Funktion mit dem Mausrrad?

**Comment by Michael-Stuehle** [comment]
gibt es schon... 
ist halt strg + mausrad

**Comment by Michael-Stuehle** [comment]
größtenteils fertig, eventuell noch extra style änderungen nötig
