### ISSUE TITLE
2d karte: Build template anpassen, sodass dark-mode funktioniert

### ISSUE THREAD

**Issue by Michael-Stuehle** [Michael-Stuehle/wilken_maps#26]
das Build template muss so angepasst werden, dass der dark mode funktioniert.

wichtig nicht die dateien in Node_server\public\2d\ verwenden! die sind die fertigen builds und werden immer wieder überschrieben.
build TEMPLATE ist in
2d karte\Assets\WebGLTemplates\newTemplate\

einfach script einbinden:
<script src="/script.js"></script>	

dieses setzt dann automatisch die folgenden im css verwendbaren variablen:
--btnBackgroundColor
--btnColor
--btnHoverColor
--textColor
--backgroundColor
--settingIconColor
--linkColor
--borderColor

**Comment by bewerne** [comment]
Hab es implementiert und committet

**Comment by Michael-Stuehle** [comment]
neues wilken logo ist eingebaut
